Repository emcek/dcspy, pull requests merged in 2024-03, with the labels that each got.

#272 Remnove 'physical_variant' and `momentary_positions`
  .pre-commit-config.yaml
  CHANGELOG.md
  dcspy/models.py
  dcspy/qt_gui.py
  requirements_test.txt
  tests/resources/DCS.openbeta/Scripts/DCS-BIOS/doc/json/A-10C.json
  tests/resources/DCS.openbeta/Scripts/DCS-BIOS/doc/json/AH-64D.json
  tests/resources/DCS.openbeta/Scripts/DCS-BIOS/doc/json/AV8BNA.json
  tests/resources/DCS.openbeta/Scripts/DCS-BIOS/doc/json/F-14.json
  tests/resources/DCS.openbeta/Scripts/DCS-BIOS/doc/json/F-15E.json
  tests/resources/DCS.openbeta/Scripts/DCS-BIOS/doc/json/F-16C_50.json
  tests/resources/DCS.openbeta/Scripts/DCS-BIOS/doc/json/FA-18C_hornet.json
  tests/resources/DCS.openbeta/Scripts/DCS-BIOS/doc/json/Ka-50.json
  tests/resources/DCS.openbeta/Scripts/DCS-BIOS/doc/json/Mi-24P.json
  tests/resources/DCS.openbeta/Scripts/DCS-BIOS/doc/json/Mi-8MT.json
  tests/resources/DCS.openbeta/Scripts/DCS-BIOS/doc/json/NS430.json
  tests/test_models.py
  uml/classes.puml
Labels: internal

#274 Ignore key up events if they are not for push button actions
  dcspy/logitech.py
  dcspy/models.py
  tests/test_aircraft.py
  tests/test_logitech.py
  tests/test_models.py
Labels: bug, internal

#273 Bug fixing for 3.2.0
  CHANGELOG.md
  dcspy/aircraft.py
  dcspy/logitech.py
  dcspy/models.py
  dcspy/utils.py
  tests/conftest.py
  tests/helpers.py
  tests/resources/linux/ah64dblkii_color_pre_mode.png
  tests/resources/linux/ah64dblkii_mono_pre_mode.png
  tests/resources/linux/ka503_color_Ka503.png
  tests/resources/linux/ka503_mono_Ka503.png
  tests/resources/linux/ka50_color_Ka50.png
  tests/resources/linux/ka50_mono_Ka50.png
  tests/resources/linux/mi24p_color_Mi24P.png
  tests/resources/linux/mi24p_mono_Mi24P.png
  tests/resources/linux/mi8mt_color_Mi8MT.png
  tests/resources/linux/mi8mt_mono_Mi8MT.png
  tests/resources/win32/ah64dblkii_color_pre_mode.png
  tests/resources/win32/ah64dblkii_mono_pre_mode.png
  tests/resources/win32/ka503_color_Ka503.png
  tests/resources/win32/ka503_mono_Ka503.png
  tests/resources/win32/ka50_color_Ka50.png
  tests/resources/win32/ka50_mono_Ka50.png
  tests/resources/win32/mi24p_color_Mi24P.png
  tests/resources/win32/mi24p_mono_Mi24P.png
  tests/resources/win32/mi8mt_color_Mi8MT.png
  tests/resources/win32/mi8mt_mono_Mi8MT.png
  tests/test_aircraft.py
  tests/test_logitech.py
  tests/test_models.py
  tests/test_utils.py
Labels: bug, internal

#279 Unload previous airplane
  .pre-commit-config.yaml
  CHANGELOG.md
  dcspy/dcsbios.py
  dcspy/logitech.py
  dcspy/starter.py
  requirements_test.txt
  tests/test_logitech.py
Labels: enhancement

#280 Test DCS-BIOS full flow
  dcspy/models.py
  dcspy/utils.py
  pyproject.toml
  tests/helpers.py
  tests/resources/dcs_bios_data.json
  tests/test_starter.py
Labels: internal

#286 Make LCD optional
  dcs_py.py
  dcspy/aircraft.py
  dcspy/logitech.py
  dcspy/qt_gui.py
  dcspy/run.py
  dcspy/sdk/key_sdk.py
  dcspy/sdk/lcd_sdk.py
  dcspy/starter.py
  tests/conftest.py
  tests/helpers.py
  tests/test_aircraft.py
  tests/test_key_sdk.py
  tests/test_lcd_sdk.py
  tests/test_logitech.py
  uml/classes.puml
Labels: enhancement, internal

#287 Rename exec during CI process
  .github/workflows/release-ci.yml
  .pre-commit-config.yaml
  CHANGELOG.md
  dcspy.spec
  dcspy/qt_gui.py
  dcspy_cli.spec
  dcspy_onedir.spec
  requirements_test.txt
Labels: internal
