Repository emcek/dcspy, pull requests merged in 2024-02, with the labels that each got.

#255 Update Pydantic
  pyproject.toml
  requirements.txt
  requirements_test.txt
Labels: internal

#257 Wrong type for request
  CHANGELOG.md
  dcspy/models.py
  tests/test_models.py
Labels: bug

#258 Add support for push button actions
  dcspy/aircraft.py
Labels: enhancement
